// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/v1/areaPolygon.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAreaPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int64  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int64  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RegionId uint64 `protobuf:"varint,3,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
}

func (x *ListAreaPolygonRequest) Reset() {
	*x = ListAreaPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_areaPolygon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaPolygonRequest) ProtoMessage() {}

func (x *ListAreaPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_areaPolygon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaPolygonRequest.ProtoReflect.Descriptor instead.
func (*ListAreaPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_areaPolygon_proto_rawDescGZIP(), []int{0}
}

func (x *ListAreaPolygonRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAreaPolygonRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAreaPolygonRequest) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

type ListAreaPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items      []*ListAreaPolygonReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount uint64                       `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page       uint64                       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize   uint64                       `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FirstPage  bool                         `protobuf:"varint,5,opt,name=first_page,json=firstPage,proto3" json:"first_page,omitempty"`
	LastPage   bool                         `protobuf:"varint,6,opt,name=last_page,json=lastPage,proto3" json:"last_page,omitempty"`
	PrevPage   int64                        `protobuf:"varint,7,opt,name=prev_page,json=prevPage,proto3" json:"prev_page,omitempty"`
	NextPage   int64                        `protobuf:"varint,8,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
}

func (x *ListAreaPolygonReply) Reset() {
	*x = ListAreaPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_areaPolygon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaPolygonReply) ProtoMessage() {}

func (x *ListAreaPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_areaPolygon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaPolygonReply.ProtoReflect.Descriptor instead.
func (*ListAreaPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_v1_areaPolygon_proto_rawDescGZIP(), []int{1}
}

func (x *ListAreaPolygonReply) GetItems() []*ListAreaPolygonReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAreaPolygonReply) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListAreaPolygonReply) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAreaPolygonReply) GetPageSize() uint64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAreaPolygonReply) GetFirstPage() bool {
	if x != nil {
		return x.FirstPage
	}
	return false
}

func (x *ListAreaPolygonReply) GetLastPage() bool {
	if x != nil {
		return x.LastPage
	}
	return false
}

func (x *ListAreaPolygonReply) GetPrevPage() int64 {
	if x != nil {
		return x.PrevPage
	}
	return 0
}

func (x *ListAreaPolygonReply) GetNextPage() int64 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

type GetAreaPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAreaPolygonRequest) Reset() {
	*x = GetAreaPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_areaPolygon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaPolygonRequest) ProtoMessage() {}

func (x *GetAreaPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_areaPolygon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaPolygonRequest.ProtoReflect.Descriptor instead.
func (*GetAreaPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_areaPolygon_proto_rawDescGZIP(), []int{2}
}

func (x *GetAreaPolygonRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAreaPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionId   uint64 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Lat        string `protobuf:"bytes,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng        string `protobuf:"bytes,4,opt,name=lng,proto3" json:"lng,omitempty"`
	CreateTime uint64 `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime uint64 `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *GetAreaPolygonReply) Reset() {
	*x = GetAreaPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_areaPolygon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaPolygonReply) ProtoMessage() {}

func (x *GetAreaPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_areaPolygon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaPolygonReply.ProtoReflect.Descriptor instead.
func (*GetAreaPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_v1_areaPolygon_proto_rawDescGZIP(), []int{3}
}

func (x *GetAreaPolygonReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAreaPolygonReply) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *GetAreaPolygonReply) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *GetAreaPolygonReply) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *GetAreaPolygonReply) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GetAreaPolygonReply) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type ListAreaPolygonReply_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionId   uint64 `protobuf:"varint,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Lat        string `protobuf:"bytes,3,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng        string `protobuf:"bytes,4,opt,name=lng,proto3" json:"lng,omitempty"`
	UpdateTime uint64 `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *ListAreaPolygonReply_Item) Reset() {
	*x = ListAreaPolygonReply_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_areaPolygon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaPolygonReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaPolygonReply_Item) ProtoMessage() {}

func (x *ListAreaPolygonReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_areaPolygon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaPolygonReply_Item.ProtoReflect.Descriptor instead.
func (*ListAreaPolygonReply_Item) Descriptor() ([]byte, []int) {
	return file_api_v1_areaPolygon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListAreaPolygonReply_Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListAreaPolygonReply_Item) GetRegionId() uint64 {
	if x != nil {
		return x.RegionId
	}
	return 0
}

func (x *ListAreaPolygonReply_Item) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *ListAreaPolygonReply_Item) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *ListAreaPolygonReply_Item) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_api_v1_areaPolygon_proto protoreflect.FileDescriptor

var file_api_v1_areaPolygon_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x22, 0x66, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x91, 0x03, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72,
	0x65, 0x76, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x72, 0x65, 0x76, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x78, 0x74, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6e, 0x65, 0x78, 0x74,
	0x50, 0x61, 0x67, 0x65, 0x1a, 0x78, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x1f, 0x0a,
	0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x27,
	0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41,
	0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x32, 0xac, 0x01, 0x0a, 0x0b, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67,
	0x6f, 0x6e, 0x12, 0x4f, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x35, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x29, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6e, 0x61, 0x72, 0x74, 0x6c,
	0x75, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_areaPolygon_proto_rawDescOnce sync.Once
	file_api_v1_areaPolygon_proto_rawDescData = file_api_v1_areaPolygon_proto_rawDesc
)

func file_api_v1_areaPolygon_proto_rawDescGZIP() []byte {
	file_api_v1_areaPolygon_proto_rawDescOnce.Do(func() {
		file_api_v1_areaPolygon_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_areaPolygon_proto_rawDescData)
	})
	return file_api_v1_areaPolygon_proto_rawDescData
}

var file_api_v1_areaPolygon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_areaPolygon_proto_goTypes = []interface{}{
	(*ListAreaPolygonRequest)(nil),    // 0: api.v1.ListAreaPolygonRequest
	(*ListAreaPolygonReply)(nil),      // 1: api.v1.ListAreaPolygonReply
	(*GetAreaPolygonRequest)(nil),     // 2: api.v1.GetAreaPolygonRequest
	(*GetAreaPolygonReply)(nil),       // 3: api.v1.GetAreaPolygonReply
	(*ListAreaPolygonReply_Item)(nil), // 4: api.v1.ListAreaPolygonReply.Item
}
var file_api_v1_areaPolygon_proto_depIdxs = []int32{
	4, // 0: api.v1.ListAreaPolygonReply.items:type_name -> api.v1.ListAreaPolygonReply.Item
	0, // 1: api.v1.AreaPolygon.ListAreaPolygon:input_type -> api.v1.ListAreaPolygonRequest
	2, // 2: api.v1.AreaPolygon.GetAreaPolygon:input_type -> api.v1.GetAreaPolygonRequest
	1, // 3: api.v1.AreaPolygon.ListAreaPolygon:output_type -> api.v1.ListAreaPolygonReply
	3, // 4: api.v1.AreaPolygon.GetAreaPolygon:output_type -> api.v1.GetAreaPolygonReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_v1_areaPolygon_proto_init() }
func file_api_v1_areaPolygon_proto_init() {
	if File_api_v1_areaPolygon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_areaPolygon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_areaPolygon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_areaPolygon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_areaPolygon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_areaPolygon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaPolygonReply_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_areaPolygon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_areaPolygon_proto_goTypes,
		DependencyIndexes: file_api_v1_areaPolygon_proto_depIdxs,
		MessageInfos:      file_api_v1_areaPolygon_proto_msgTypes,
	}.Build()
	File_api_v1_areaPolygon_proto = out.File
	file_api_v1_areaPolygon_proto_rawDesc = nil
	file_api_v1_areaPolygon_proto_goTypes = nil
	file_api_v1_areaPolygon_proto_depIdxs = nil
}
