// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: api/v1/area.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Parent:
	//	*ListAreaRequest_ParentId
	//	*ListAreaRequest_RegionId
	Parent isListAreaRequest_Parent `protobuf_oneof:"parent"`
	Level  int32                    `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Kw     string                   `protobuf:"bytes,4,opt,name=kw,proto3" json:"kw,omitempty"`
	Order  string                   `protobuf:"bytes,9,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *ListAreaRequest) Reset() {
	*x = ListAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaRequest) ProtoMessage() {}

func (x *ListAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaRequest.ProtoReflect.Descriptor instead.
func (*ListAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{0}
}

func (m *ListAreaRequest) GetParent() isListAreaRequest_Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (x *ListAreaRequest) GetParentId() uint64 {
	if x, ok := x.GetParent().(*ListAreaRequest_ParentId); ok {
		return x.ParentId
	}
	return 0
}

func (x *ListAreaRequest) GetRegionId() string {
	if x, ok := x.GetParent().(*ListAreaRequest_RegionId); ok {
		return x.RegionId
	}
	return ""
}

func (x *ListAreaRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ListAreaRequest) GetKw() string {
	if x != nil {
		return x.Kw
	}
	return ""
}

func (x *ListAreaRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type isListAreaRequest_Parent interface {
	isListAreaRequest_Parent()
}

type ListAreaRequest_ParentId struct {
	ParentId uint64 `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3,oneof"`
}

type ListAreaRequest_RegionId struct {
	RegionId string `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3,oneof"`
}

func (*ListAreaRequest_ParentId) isListAreaRequest_Parent() {}

func (*ListAreaRequest_RegionId) isListAreaRequest_Parent() {}

type ListAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ListAreaReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ListAreaReply) Reset() {
	*x = ListAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaReply) ProtoMessage() {}

func (x *ListAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaReply.ProtoReflect.Descriptor instead.
func (*ListAreaReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{1}
}

func (x *ListAreaReply) GetItems() []*ListAreaReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Parent:
	//	*GetAreaRequest_Id
	//	*GetAreaRequest_RegionId
	Parent isGetAreaRequest_Parent `protobuf_oneof:"parent"`
	Level  uint32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *GetAreaRequest) Reset() {
	*x = GetAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaRequest) ProtoMessage() {}

func (x *GetAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaRequest.ProtoReflect.Descriptor instead.
func (*GetAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{2}
}

func (m *GetAreaRequest) GetParent() isGetAreaRequest_Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (x *GetAreaRequest) GetId() uint64 {
	if x, ok := x.GetParent().(*GetAreaRequest_Id); ok {
		return x.Id
	}
	return 0
}

func (x *GetAreaRequest) GetRegionId() string {
	if x, ok := x.GetParent().(*GetAreaRequest_RegionId); ok {
		return x.RegionId
	}
	return ""
}

func (x *GetAreaRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type isGetAreaRequest_Parent interface {
	isGetAreaRequest_Parent()
}

type GetAreaRequest_Id struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type GetAreaRequest_RegionId struct {
	RegionId string `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3,oneof"`
}

func (*GetAreaRequest_Id) isGetAreaRequest_Parent() {}

func (*GetAreaRequest_RegionId) isGetAreaRequest_Parent() {}

type GetAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionId   string        `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Title      string        `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Lat        string        `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng        string        `protobuf:"bytes,5,opt,name=lng,proto3" json:"lng,omitempty"`
	Ucfirst    string        `protobuf:"bytes,6,opt,name=ucfirst,proto3" json:"ucfirst,omitempty"`
	Pinyin     string        `protobuf:"bytes,7,opt,name=pinyin,proto3" json:"pinyin,omitempty"`
	CityCode   string        `protobuf:"bytes,8,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	ZipCode    string        `protobuf:"bytes,9,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Level      uint32        `protobuf:"varint,10,opt,name=level,proto3" json:"level,omitempty"`
	CreateTime uint64        `protobuf:"varint,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime uint64        `protobuf:"varint,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Parent     *GetAreaReply `protobuf:"bytes,13,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *GetAreaReply) Reset() {
	*x = GetAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaReply) ProtoMessage() {}

func (x *GetAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaReply.ProtoReflect.Descriptor instead.
func (*GetAreaReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{3}
}

func (x *GetAreaReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetAreaReply) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *GetAreaReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetAreaReply) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *GetAreaReply) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *GetAreaReply) GetUcfirst() string {
	if x != nil {
		return x.Ucfirst
	}
	return ""
}

func (x *GetAreaReply) GetPinyin() string {
	if x != nil {
		return x.Pinyin
	}
	return ""
}

func (x *GetAreaReply) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *GetAreaReply) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *GetAreaReply) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetAreaReply) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *GetAreaReply) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *GetAreaReply) GetParent() *GetAreaReply {
	if x != nil {
		return x.Parent
	}
	return nil
}

type CascadeListAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Parent:
	//	*CascadeListAreaRequest_Id
	//	*CascadeListAreaRequest_RegionId
	Parent isCascadeListAreaRequest_Parent `protobuf_oneof:"parent"`
	Level  int32                           `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Deep   int32                           `protobuf:"varint,4,opt,name=deep,proto3" json:"deep,omitempty"`
	Kw     string                          `protobuf:"bytes,5,opt,name=kw,proto3" json:"kw,omitempty"`
}

func (x *CascadeListAreaRequest) Reset() {
	*x = CascadeListAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CascadeListAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CascadeListAreaRequest) ProtoMessage() {}

func (x *CascadeListAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CascadeListAreaRequest.ProtoReflect.Descriptor instead.
func (*CascadeListAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{4}
}

func (m *CascadeListAreaRequest) GetParent() isCascadeListAreaRequest_Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (x *CascadeListAreaRequest) GetId() uint64 {
	if x, ok := x.GetParent().(*CascadeListAreaRequest_Id); ok {
		return x.Id
	}
	return 0
}

func (x *CascadeListAreaRequest) GetRegionId() string {
	if x, ok := x.GetParent().(*CascadeListAreaRequest_RegionId); ok {
		return x.RegionId
	}
	return ""
}

func (x *CascadeListAreaRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CascadeListAreaRequest) GetDeep() int32 {
	if x != nil {
		return x.Deep
	}
	return 0
}

func (x *CascadeListAreaRequest) GetKw() string {
	if x != nil {
		return x.Kw
	}
	return ""
}

type isCascadeListAreaRequest_Parent interface {
	isCascadeListAreaRequest_Parent()
}

type CascadeListAreaRequest_Id struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3,oneof"`
}

type CascadeListAreaRequest_RegionId struct {
	RegionId string `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3,oneof"`
}

func (*CascadeListAreaRequest_Id) isCascadeListAreaRequest_Parent() {}

func (*CascadeListAreaRequest_RegionId) isCascadeListAreaRequest_Parent() {}

type CascadeListAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items  []*CascadeListAreaReply_Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Parent *CascadeListAreaReply_Item   `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *CascadeListAreaReply) Reset() {
	*x = CascadeListAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CascadeListAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CascadeListAreaReply) ProtoMessage() {}

func (x *CascadeListAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CascadeListAreaReply.ProtoReflect.Descriptor instead.
func (*CascadeListAreaReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{5}
}

func (x *CascadeListAreaReply) GetItems() []*CascadeListAreaReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CascadeListAreaReply) GetParent() *CascadeListAreaReply_Item {
	if x != nil {
		return x.Parent
	}
	return nil
}

type CreateAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Parent:
	//	*CreateAreaRequest_ParentId
	//	*CreateAreaRequest_ParentRegionId
	Parent         isCreateAreaRequest_Parent `protobuf_oneof:"parent"`
	RegionId       string                     `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Title          string                     `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Lat            string                     `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng            string                     `protobuf:"bytes,5,opt,name=lng,proto3" json:"lng,omitempty"`
	CityCode       string                     `protobuf:"bytes,6,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	ZipCode        string                     `protobuf:"bytes,7,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	ChildrenNumber uint32                     `protobuf:"varint,8,opt,name=children_number,json=childrenNumber,proto3" json:"children_number,omitempty"`
	ParentLevel    int32                      `protobuf:"varint,11,opt,name=parent_level,json=parentLevel,proto3" json:"parent_level,omitempty"`
}

func (x *CreateAreaRequest) Reset() {
	*x = CreateAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaRequest) ProtoMessage() {}

func (x *CreateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaRequest.ProtoReflect.Descriptor instead.
func (*CreateAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{6}
}

func (m *CreateAreaRequest) GetParent() isCreateAreaRequest_Parent {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (x *CreateAreaRequest) GetParentId() uint64 {
	if x, ok := x.GetParent().(*CreateAreaRequest_ParentId); ok {
		return x.ParentId
	}
	return 0
}

func (x *CreateAreaRequest) GetParentRegionId() string {
	if x, ok := x.GetParent().(*CreateAreaRequest_ParentRegionId); ok {
		return x.ParentRegionId
	}
	return ""
}

func (x *CreateAreaRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *CreateAreaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAreaRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *CreateAreaRequest) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *CreateAreaRequest) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *CreateAreaRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *CreateAreaRequest) GetChildrenNumber() uint32 {
	if x != nil {
		return x.ChildrenNumber
	}
	return 0
}

func (x *CreateAreaRequest) GetParentLevel() int32 {
	if x != nil {
		return x.ParentLevel
	}
	return 0
}

type isCreateAreaRequest_Parent interface {
	isCreateAreaRequest_Parent()
}

type CreateAreaRequest_ParentId struct {
	ParentId uint64 `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3,oneof"`
}

type CreateAreaRequest_ParentRegionId struct {
	ParentRegionId string `protobuf:"bytes,10,opt,name=parent_region_id,json=parentRegionId,proto3,oneof"`
}

func (*CreateAreaRequest_ParentId) isCreateAreaRequest_Parent() {}

func (*CreateAreaRequest_ParentRegionId) isCreateAreaRequest_Parent() {}

type CreateAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateAreaReply) Reset() {
	*x = CreateAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaReply) ProtoMessage() {}

func (x *CreateAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaReply.ProtoReflect.Descriptor instead.
func (*CreateAreaReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAreaReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId       string `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	RegionId       string `protobuf:"bytes,3,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Title          string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Lat            string `protobuf:"bytes,5,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng            string `protobuf:"bytes,6,opt,name=lng,proto3" json:"lng,omitempty"`
	CityCode       string `protobuf:"bytes,7,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	ZipCode        string `protobuf:"bytes,8,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	ChildrenNumber uint32 `protobuf:"varint,9,opt,name=children_number,json=childrenNumber,proto3" json:"children_number,omitempty"`
}

func (x *UpdateAreaRequest) Reset() {
	*x = UpdateAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaRequest) ProtoMessage() {}

func (x *UpdateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaRequest.ProtoReflect.Descriptor instead.
func (*UpdateAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAreaRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAreaRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *UpdateAreaRequest) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *UpdateAreaRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateAreaRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *UpdateAreaRequest) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *UpdateAreaRequest) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *UpdateAreaRequest) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *UpdateAreaRequest) GetChildrenNumber() uint32 {
	if x != nil {
		return x.ChildrenNumber
	}
	return 0
}

type UpdateAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UpdateAreaReply) Reset() {
	*x = UpdateAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaReply) ProtoMessage() {}

func (x *UpdateAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaReply.ProtoReflect.Descriptor instead.
func (*UpdateAreaReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAreaReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ids []uint64 `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DeleteAreaRequest) Reset() {
	*x = DeleteAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaRequest) ProtoMessage() {}

func (x *DeleteAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaRequest.ProtoReflect.Descriptor instead.
func (*DeleteAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAreaRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteAreaRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAreaReply) Reset() {
	*x = DeleteAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaReply) ProtoMessage() {}

func (x *DeleteAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaReply.ProtoReflect.Descriptor instead.
func (*DeleteAreaReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{11}
}

type ListAreaReply_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionId   string `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Title      string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Ucfirst    string `protobuf:"bytes,5,opt,name=ucfirst,proto3" json:"ucfirst,omitempty"`
	Pinyin     string `protobuf:"bytes,6,opt,name=pinyin,proto3" json:"pinyin,omitempty"`
	CityCode   string `protobuf:"bytes,7,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	ZipCode    string `protobuf:"bytes,8,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	Level      uint32 `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
	UpdateTime uint64 `protobuf:"varint,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *ListAreaReply_Item) Reset() {
	*x = ListAreaReply_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaReply_Item) ProtoMessage() {}

func (x *ListAreaReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaReply_Item.ProtoReflect.Descriptor instead.
func (*ListAreaReply_Item) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListAreaReply_Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListAreaReply_Item) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *ListAreaReply_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ListAreaReply_Item) GetUcfirst() string {
	if x != nil {
		return x.Ucfirst
	}
	return ""
}

func (x *ListAreaReply_Item) GetPinyin() string {
	if x != nil {
		return x.Pinyin
	}
	return ""
}

func (x *ListAreaReply_Item) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *ListAreaReply_Item) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *ListAreaReply_Item) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ListAreaReply_Item) GetUpdateTime() uint64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type CascadeListAreaReply_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegionId string                       `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	Title    string                       `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Lat      string                       `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng      string                       `protobuf:"bytes,5,opt,name=lng,proto3" json:"lng,omitempty"`
	Ucfirst  string                       `protobuf:"bytes,6,opt,name=ucfirst,proto3" json:"ucfirst,omitempty"`
	Pinyin   string                       `protobuf:"bytes,7,opt,name=pinyin,proto3" json:"pinyin,omitempty"`
	Level    uint32                       `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	Items    []*CascadeListAreaReply_Item `protobuf:"bytes,9,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *CascadeListAreaReply_Item) Reset() {
	*x = CascadeListAreaReply_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CascadeListAreaReply_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CascadeListAreaReply_Item) ProtoMessage() {}

func (x *CascadeListAreaReply_Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CascadeListAreaReply_Item.ProtoReflect.Descriptor instead.
func (*CascadeListAreaReply_Item) Descriptor() ([]byte, []int) {
	return file_api_v1_area_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CascadeListAreaReply_Item) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CascadeListAreaReply_Item) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *CascadeListAreaReply_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CascadeListAreaReply_Item) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *CascadeListAreaReply_Item) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

func (x *CascadeListAreaReply_Item) GetUcfirst() string {
	if x != nil {
		return x.Ucfirst
	}
	return ""
}

func (x *CascadeListAreaReply_Item) GetPinyin() string {
	if x != nil {
		return x.Pinyin
	}
	return ""
}

func (x *CascadeListAreaReply_Item) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CascadeListAreaReply_Item) GetItems() []*CascadeListAreaReply_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_v1_area_proto protoreflect.FileDescriptor

var file_api_v1_area_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x95, 0x01, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x00, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x6b, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x6b, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x08, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x22, 0xae, 0x02, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0xea, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x63, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x63, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x69, 0x6e, 0x79, 0x69, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x69, 0x6e, 0x79, 0x69, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x61, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x08, 0x0a,
	0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22, 0xe5, 0x02, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6c, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x75, 0x63, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x75, 0x63, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x6e,
	0x79, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x69, 0x6e, 0x79, 0x69,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x2c, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22,
	0x8d, 0x01, 0x0a, 0x16, 0x43, 0x61, 0x73, 0x63, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x09,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x65, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x64, 0x65, 0x65, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x6b, 0x77, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x6b, 0x77, 0x42, 0x08, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x22,
	0xfb, 0x02, 0x0a, 0x14, 0x43, 0x61, 0x73, 0x63, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x61, 0x73, 0x63, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x73, 0x63, 0x61,
	0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x1a, 0xee, 0x01, 0x0a,
	0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e,
	0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x75, 0x63, 0x66, 0x69, 0x72, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75,
	0x63, 0x66, 0x69, 0x72, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x69, 0x6e, 0x79, 0x69, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x69, 0x6e, 0x79, 0x69, 0x6e, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x37, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x73,
	0x63, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xc3, 0x02,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0e,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6c, 0x6e, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x42, 0x08, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x22, 0x21, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf8, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6c, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x7a, 0x69, 0x70, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x7a, 0x69, 0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x21, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72,
	0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x87,
	0x03, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x38, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x36, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0b, 0x43, 0x61, 0x73,
	0x63, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x73, 0x63, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x61, 0x73, 0x63, 0x61, 0x64, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x35, 0x0a, 0x06, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x50, 0x01, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x63, 0x6e, 0x61, 0x72, 0x74, 0x6c, 0x75, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_area_proto_rawDescOnce sync.Once
	file_api_v1_area_proto_rawDescData = file_api_v1_area_proto_rawDesc
)

func file_api_v1_area_proto_rawDescGZIP() []byte {
	file_api_v1_area_proto_rawDescOnce.Do(func() {
		file_api_v1_area_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_area_proto_rawDescData)
	})
	return file_api_v1_area_proto_rawDescData
}

var file_api_v1_area_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_v1_area_proto_goTypes = []interface{}{
	(*ListAreaRequest)(nil),           // 0: api.v1.ListAreaRequest
	(*ListAreaReply)(nil),             // 1: api.v1.ListAreaReply
	(*GetAreaRequest)(nil),            // 2: api.v1.GetAreaRequest
	(*GetAreaReply)(nil),              // 3: api.v1.GetAreaReply
	(*CascadeListAreaRequest)(nil),    // 4: api.v1.CascadeListAreaRequest
	(*CascadeListAreaReply)(nil),      // 5: api.v1.CascadeListAreaReply
	(*CreateAreaRequest)(nil),         // 6: api.v1.CreateAreaRequest
	(*CreateAreaReply)(nil),           // 7: api.v1.CreateAreaReply
	(*UpdateAreaRequest)(nil),         // 8: api.v1.UpdateAreaRequest
	(*UpdateAreaReply)(nil),           // 9: api.v1.UpdateAreaReply
	(*DeleteAreaRequest)(nil),         // 10: api.v1.DeleteAreaRequest
	(*DeleteAreaReply)(nil),           // 11: api.v1.DeleteAreaReply
	(*ListAreaReply_Item)(nil),        // 12: api.v1.ListAreaReply.Item
	(*CascadeListAreaReply_Item)(nil), // 13: api.v1.CascadeListAreaReply.Item
}
var file_api_v1_area_proto_depIdxs = []int32{
	12, // 0: api.v1.ListAreaReply.items:type_name -> api.v1.ListAreaReply.Item
	3,  // 1: api.v1.GetAreaReply.parent:type_name -> api.v1.GetAreaReply
	13, // 2: api.v1.CascadeListAreaReply.items:type_name -> api.v1.CascadeListAreaReply.Item
	13, // 3: api.v1.CascadeListAreaReply.parent:type_name -> api.v1.CascadeListAreaReply.Item
	13, // 4: api.v1.CascadeListAreaReply.Item.items:type_name -> api.v1.CascadeListAreaReply.Item
	0,  // 5: api.v1.Area.List:input_type -> api.v1.ListAreaRequest
	2,  // 6: api.v1.Area.View:input_type -> api.v1.GetAreaRequest
	4,  // 7: api.v1.Area.CascadeList:input_type -> api.v1.CascadeListAreaRequest
	6,  // 8: api.v1.Area.Create:input_type -> api.v1.CreateAreaRequest
	8,  // 9: api.v1.Area.Update:input_type -> api.v1.UpdateAreaRequest
	10, // 10: api.v1.Area.Delete:input_type -> api.v1.DeleteAreaRequest
	1,  // 11: api.v1.Area.List:output_type -> api.v1.ListAreaReply
	3,  // 12: api.v1.Area.View:output_type -> api.v1.GetAreaReply
	5,  // 13: api.v1.Area.CascadeList:output_type -> api.v1.CascadeListAreaReply
	7,  // 14: api.v1.Area.Create:output_type -> api.v1.CreateAreaReply
	9,  // 15: api.v1.Area.Update:output_type -> api.v1.UpdateAreaReply
	11, // 16: api.v1.Area.Delete:output_type -> api.v1.DeleteAreaReply
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_area_proto_init() }
func file_api_v1_area_proto_init() {
	if File_api_v1_area_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_area_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CascadeListAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CascadeListAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaReply_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CascadeListAreaReply_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_v1_area_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ListAreaRequest_ParentId)(nil),
		(*ListAreaRequest_RegionId)(nil),
	}
	file_api_v1_area_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*GetAreaRequest_Id)(nil),
		(*GetAreaRequest_RegionId)(nil),
	}
	file_api_v1_area_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*CascadeListAreaRequest_Id)(nil),
		(*CascadeListAreaRequest_RegionId)(nil),
	}
	file_api_v1_area_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*CreateAreaRequest_ParentId)(nil),
		(*CreateAreaRequest_ParentRegionId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_area_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_area_proto_goTypes,
		DependencyIndexes: file_api_v1_area_proto_depIdxs,
		MessageInfos:      file_api_v1_area_proto_msgTypes,
	}.Build()
	File_api_v1_area_proto = out.File
	file_api_v1_area_proto_rawDesc = nil
	file_api_v1_area_proto_goTypes = nil
	file_api_v1_area_proto_depIdxs = nil
}
