// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.1

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type CountryHTTPServer interface {
	GetCountry(context.Context, *GetCountryRequest) (*GetCountryReply, error)
	ListCountry(context.Context, *ListCountryRequest) (*ListCountryReply, error)
}

func RegisterCountryHTTPServer(s *http.Server, srv CountryHTTPServer) {
	r := s.Route("/")
	r.GET("/country/list", _Country_ListCountry0_HTTP_Handler(srv))
	r.GET("/country/uuid/{uuid}", _Country_GetCountry0_HTTP_Handler(srv))
	r.GET("/country/code/{code}", _Country_GetCountry1_HTTP_Handler(srv))
	r.GET("/country/number/{number_code}", _Country_GetCountry2_HTTP_Handler(srv))
	r.GET("/country/view", _Country_GetCountry3_HTTP_Handler(srv))
}

func _Country_ListCountry0_HTTP_Handler(srv CountryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCountryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.v1.Country/ListCountry")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCountry(ctx, req.(*ListCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCountryReply)
		return ctx.Result(200, reply)
	}
}

func _Country_GetCountry0_HTTP_Handler(srv CountryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCountryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.v1.Country/GetCountry")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCountry(ctx, req.(*GetCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCountryReply)
		return ctx.Result(200, reply)
	}
}

func _Country_GetCountry1_HTTP_Handler(srv CountryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCountryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.v1.Country/GetCountry")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCountry(ctx, req.(*GetCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCountryReply)
		return ctx.Result(200, reply)
	}
}

func _Country_GetCountry2_HTTP_Handler(srv CountryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCountryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.v1.Country/GetCountry")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCountry(ctx, req.(*GetCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCountryReply)
		return ctx.Result(200, reply)
	}
}

func _Country_GetCountry3_HTTP_Handler(srv CountryHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCountryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.v1.Country/GetCountry")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCountry(ctx, req.(*GetCountryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCountryReply)
		return ctx.Result(200, reply)
	}
}

type CountryHTTPClient interface {
	GetCountry(ctx context.Context, req *GetCountryRequest, opts ...http.CallOption) (rsp *GetCountryReply, err error)
	ListCountry(ctx context.Context, req *ListCountryRequest, opts ...http.CallOption) (rsp *ListCountryReply, err error)
}

type CountryHTTPClientImpl struct {
	cc *http.Client
}

func NewCountryHTTPClient(client *http.Client) CountryHTTPClient {
	return &CountryHTTPClientImpl{client}
}

func (c *CountryHTTPClientImpl) GetCountry(ctx context.Context, in *GetCountryRequest, opts ...http.CallOption) (*GetCountryReply, error) {
	var out GetCountryReply
	pattern := "/country/view"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.v1.Country/GetCountry"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *CountryHTTPClientImpl) ListCountry(ctx context.Context, in *ListCountryRequest, opts ...http.CallOption) (*ListCountryReply, error) {
	var out ListCountryReply
	pattern := "/country/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.v1.Country/ListCountry"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
