// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package tests

import (
	component2 "github.com/cnartlu/area-service/internal/component"
	"github.com/cnartlu/area-service/internal/config"
	"github.com/cnartlu/area-service/internal/cron"
	"github.com/cnartlu/area-service/pkg/component"
	"github.com/cnartlu/area-service/pkg/component/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() (*Tests, func(), error) {
	logger, err := log.NewDefault()
	if err != nil {
		return nil, nil, err
	}
	configConfig, cleanup, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	tests := New(logger, configConfig)
	return tests, func() {
		cleanup()
	}, nil
}

// wire.go:

var providerSet = wire.NewSet(log.NewDefault, config.ProviderSet, component.ProviderSet, component2.ProviderSet, cron.ProviderSet)
