debug: true
env: development
name: kk
proxy: http://127.0.0.1:7890
http:
  addr: :8000
  timeout: 1s
grpc:
  addr: 0.0.0.0:9000
  timeout: 30s
db:
  driver: mysql
  source: root:xingyun@tcp(127.0.0.1:3306)/ad_area_service  
redis:
  host:
  port: 6379
  read_timeout: 0.2s
  write_timeout: 0.2s
logger:
  level: warn
  stdout: true
  targets:
    file:
      type: file
      filename: logs/odsasassasassa.log
    file1:
      type: file
      filename: logs/2006-12-15.log
      level: 1
