app:
  debug: true
  env: dev
  name: kk
  proxy: http://127.0.0.1:7890
filesystem:
  
http:
  addr: :8000
  timeout: 1s
grpc:
  addr: 0.0.0.0:9000
  timeout: 30s
db:
  driver: mysql
  source: root:xingyun@tcp(127.0.0.1:3306)/ad_area_service  
redis:
  host:
  port: 6379
  read_timeout: 0.2s
  write_timeout: 0.2s
logger:
  stdout: false
  level: debug
  targets:
    debug:
      type: file
      filename: logs/debug.log
      levels: [debug]
    info:
      type: file
      filename: logs/info.log
      levels: [info]
    warning:
      type: file
      filename: logs/warning.log
      level: warning

