// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: api/console/v1/Area.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAreaRequest) Reset() {
	*x = CreateAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaRequest) ProtoMessage() {}

func (x *CreateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaRequest.ProtoReflect.Descriptor instead.
func (*CreateAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{0}
}

type CreateAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAreaReply) Reset() {
	*x = CreateAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaReply) ProtoMessage() {}

func (x *CreateAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaReply.ProtoReflect.Descriptor instead.
func (*CreateAreaReply) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{1}
}

type UpdateAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAreaRequest) Reset() {
	*x = UpdateAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaRequest) ProtoMessage() {}

func (x *UpdateAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaRequest.ProtoReflect.Descriptor instead.
func (*UpdateAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{2}
}

type UpdateAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAreaReply) Reset() {
	*x = UpdateAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaReply) ProtoMessage() {}

func (x *UpdateAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaReply.ProtoReflect.Descriptor instead.
func (*UpdateAreaReply) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{3}
}

type DeleteAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAreaRequest) Reset() {
	*x = DeleteAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaRequest) ProtoMessage() {}

func (x *DeleteAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaRequest.ProtoReflect.Descriptor instead.
func (*DeleteAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{4}
}

type DeleteAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAreaReply) Reset() {
	*x = DeleteAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaReply) ProtoMessage() {}

func (x *DeleteAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaReply.ProtoReflect.Descriptor instead.
func (*DeleteAreaReply) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{5}
}

type GetAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAreaRequest) Reset() {
	*x = GetAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaRequest) ProtoMessage() {}

func (x *GetAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaRequest.ProtoReflect.Descriptor instead.
func (*GetAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{6}
}

type GetAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAreaReply) Reset() {
	*x = GetAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaReply) ProtoMessage() {}

func (x *GetAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaReply.ProtoReflect.Descriptor instead.
func (*GetAreaReply) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{7}
}

type ListAreaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAreaRequest) Reset() {
	*x = ListAreaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaRequest) ProtoMessage() {}

func (x *ListAreaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaRequest.ProtoReflect.Descriptor instead.
func (*ListAreaRequest) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{8}
}

type ListAreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAreaReply) Reset() {
	*x = ListAreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_console_v1_Area_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaReply) ProtoMessage() {}

func (x *ListAreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_v1_Area_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaReply.ProtoReflect.Descriptor instead.
func (*ListAreaReply) Descriptor() ([]byte, []int) {
	return file_api_console_v1_Area_proto_rawDescGZIP(), []int{9}
}

var File_api_console_v1_Area_proto protoreflect.FileDescriptor

var file_api_console_v1_Area_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x41, 0x72, 0x65, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69,
	0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x13, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x11, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x91, 0x03, 0x0a, 0x04, 0x41, 0x72,
	0x65, 0x61, 0x12, 0x50, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61,
	0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x50, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72,
	0x65, 0x61, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x50, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x72, 0x65, 0x61, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x41,
	0x72, 0x65, 0x61, 0x12, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x4a, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x12, 0x1f, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x45, 0x0a,
	0x0e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x50,
	0x01, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6e,
	0x61, 0x72, 0x74, 0x6c, 0x75, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_console_v1_Area_proto_rawDescOnce sync.Once
	file_api_console_v1_Area_proto_rawDescData = file_api_console_v1_Area_proto_rawDesc
)

func file_api_console_v1_Area_proto_rawDescGZIP() []byte {
	file_api_console_v1_Area_proto_rawDescOnce.Do(func() {
		file_api_console_v1_Area_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_console_v1_Area_proto_rawDescData)
	})
	return file_api_console_v1_Area_proto_rawDescData
}

var file_api_console_v1_Area_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_console_v1_Area_proto_goTypes = []interface{}{
	(*CreateAreaRequest)(nil), // 0: api.console.v1.CreateAreaRequest
	(*CreateAreaReply)(nil),   // 1: api.console.v1.CreateAreaReply
	(*UpdateAreaRequest)(nil), // 2: api.console.v1.UpdateAreaRequest
	(*UpdateAreaReply)(nil),   // 3: api.console.v1.UpdateAreaReply
	(*DeleteAreaRequest)(nil), // 4: api.console.v1.DeleteAreaRequest
	(*DeleteAreaReply)(nil),   // 5: api.console.v1.DeleteAreaReply
	(*GetAreaRequest)(nil),    // 6: api.console.v1.GetAreaRequest
	(*GetAreaReply)(nil),      // 7: api.console.v1.GetAreaReply
	(*ListAreaRequest)(nil),   // 8: api.console.v1.ListAreaRequest
	(*ListAreaReply)(nil),     // 9: api.console.v1.ListAreaReply
}
var file_api_console_v1_Area_proto_depIdxs = []int32{
	0, // 0: api.console.v1.Area.CreateArea:input_type -> api.console.v1.CreateAreaRequest
	2, // 1: api.console.v1.Area.UpdateArea:input_type -> api.console.v1.UpdateAreaRequest
	4, // 2: api.console.v1.Area.DeleteArea:input_type -> api.console.v1.DeleteAreaRequest
	6, // 3: api.console.v1.Area.GetArea:input_type -> api.console.v1.GetAreaRequest
	8, // 4: api.console.v1.Area.ListArea:input_type -> api.console.v1.ListAreaRequest
	1, // 5: api.console.v1.Area.CreateArea:output_type -> api.console.v1.CreateAreaReply
	3, // 6: api.console.v1.Area.UpdateArea:output_type -> api.console.v1.UpdateAreaReply
	5, // 7: api.console.v1.Area.DeleteArea:output_type -> api.console.v1.DeleteAreaReply
	7, // 8: api.console.v1.Area.GetArea:output_type -> api.console.v1.GetAreaReply
	9, // 9: api.console.v1.Area.ListArea:output_type -> api.console.v1.ListAreaReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_console_v1_Area_proto_init() }
func file_api_console_v1_Area_proto_init() {
	if File_api_console_v1_Area_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_console_v1_Area_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_console_v1_Area_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_console_v1_Area_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_console_v1_Area_proto_goTypes,
		DependencyIndexes: file_api_console_v1_Area_proto_depIdxs,
		MessageInfos:      file_api_console_v1_Area_proto_msgTypes,
	}.Build()
	File_api_console_v1_Area_proto = out.File
	file_api_console_v1_Area_proto_rawDesc = nil
	file_api_console_v1_Area_proto_goTypes = nil
	file_api_console_v1_Area_proto_depIdxs = nil
}
