// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	area2 "github.com/cnartlu/area-service/internal/biz/area"
	"github.com/cnartlu/area-service/internal/component/db"
	"github.com/cnartlu/area-service/internal/config"
	"github.com/cnartlu/area-service/internal/data/area"
	"github.com/cnartlu/area-service/internal/server"
	"github.com/cnartlu/area-service/internal/service"
	"github.com/cnartlu/area-service/pkg/component/redis"
	"github.com/cnartlu/area-service/pkg/log"
)

// Injectors from wire.go:

// initApp 初始化应用
func initApp(logLogger *log.Logger, configConfig *config.Config) (*server.Server, func(), error) {
	app := configConfig.Config
	grpc := app.Grpc
	dbConfig := app.Db
	client, cleanup, err := db.NewEnt(dbConfig, logLogger)
	if err != nil {
		return nil, nil, err
	}
	redisConfig := app.Redis
	redisClient, cleanup2, err := redis.New(redisConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	areaRepo := area.NewAreaRepo(client, redisClient)
	managerUsecase := area2.NewManagerUsecase(areaRepo)
	areaService := service.NewAreaService(managerUsecase)
	grpcServer := server.NewGRPCServer(logLogger, grpc, areaService)
	http := app.Http
	httpServer := server.NewHTTPServer(logLogger, grpcServer, http)
	cron := server.NewCronServer(logLogger)
	serverServer := server.NewServer(logLogger, configConfig, grpcServer, httpServer, cron)
	return serverServer, func() {
		cleanup2()
		cleanup()
	}, nil
}
