// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: api/manage/v1/area_release_asset.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAreaReleaseAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAreaReleaseAssetRequest) Reset() {
	*x = CreateAreaReleaseAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAreaReleaseAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaReleaseAssetRequest) ProtoMessage() {}

func (x *CreateAreaReleaseAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaReleaseAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAreaReleaseAssetRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{0}
}

type CreateAreaReleaseAssetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAreaReleaseAssetReply) Reset() {
	*x = CreateAreaReleaseAssetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAreaReleaseAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaReleaseAssetReply) ProtoMessage() {}

func (x *CreateAreaReleaseAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaReleaseAssetReply.ProtoReflect.Descriptor instead.
func (*CreateAreaReleaseAssetReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{1}
}

type UpdateAreaReleaseAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAreaReleaseAssetRequest) Reset() {
	*x = UpdateAreaReleaseAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAreaReleaseAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaReleaseAssetRequest) ProtoMessage() {}

func (x *UpdateAreaReleaseAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaReleaseAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAreaReleaseAssetRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{2}
}

type UpdateAreaReleaseAssetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAreaReleaseAssetReply) Reset() {
	*x = UpdateAreaReleaseAssetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAreaReleaseAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaReleaseAssetReply) ProtoMessage() {}

func (x *UpdateAreaReleaseAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaReleaseAssetReply.ProtoReflect.Descriptor instead.
func (*UpdateAreaReleaseAssetReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{3}
}

type DeleteAreaReleaseAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAreaReleaseAssetRequest) Reset() {
	*x = DeleteAreaReleaseAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAreaReleaseAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaReleaseAssetRequest) ProtoMessage() {}

func (x *DeleteAreaReleaseAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaReleaseAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAreaReleaseAssetRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{4}
}

type DeleteAreaReleaseAssetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAreaReleaseAssetReply) Reset() {
	*x = DeleteAreaReleaseAssetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAreaReleaseAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaReleaseAssetReply) ProtoMessage() {}

func (x *DeleteAreaReleaseAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaReleaseAssetReply.ProtoReflect.Descriptor instead.
func (*DeleteAreaReleaseAssetReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{5}
}

type GetAreaReleaseAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAreaReleaseAssetRequest) Reset() {
	*x = GetAreaReleaseAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaReleaseAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaReleaseAssetRequest) ProtoMessage() {}

func (x *GetAreaReleaseAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaReleaseAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAreaReleaseAssetRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{6}
}

type GetAreaReleaseAssetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAreaReleaseAssetReply) Reset() {
	*x = GetAreaReleaseAssetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaReleaseAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaReleaseAssetReply) ProtoMessage() {}

func (x *GetAreaReleaseAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaReleaseAssetReply.ProtoReflect.Descriptor instead.
func (*GetAreaReleaseAssetReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{7}
}

type ListAreaReleaseAssetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAreaReleaseAssetRequest) Reset() {
	*x = ListAreaReleaseAssetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaReleaseAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaReleaseAssetRequest) ProtoMessage() {}

func (x *ListAreaReleaseAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaReleaseAssetRequest.ProtoReflect.Descriptor instead.
func (*ListAreaReleaseAssetRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{8}
}

type ListAreaReleaseAssetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAreaReleaseAssetReply) Reset() {
	*x = ListAreaReleaseAssetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaReleaseAssetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaReleaseAssetReply) ProtoMessage() {}

func (x *ListAreaReleaseAssetReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_release_asset_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaReleaseAssetReply.ProtoReflect.Descriptor instead.
func (*ListAreaReleaseAssetReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_release_asset_proto_rawDescGZIP(), []int{9}
}

var File_api_manage_v1_area_release_asset_proto protoreflect.FileDescriptor

var file_api_manage_v1_area_release_asset_proto_rawDesc = []byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x72, 0x65, 0x61, 0x5f, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x5f, 0x61, 0x73, 0x73,
	0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x1f, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1f, 0x0a, 0x1d, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1d, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x1b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xc7, 0x04,
	0x0a, 0x10, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x12, 0x72, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x2c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x72, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61,
	0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x72, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x12, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52,
	0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x69,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c,
	0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41,
	0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x6c, 0x0a, 0x14, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73, 0x65,
	0x74, 0x12, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x41, 0x73, 0x73,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x43, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6e, 0x61, 0x72, 0x74, 0x6c, 0x75, 0x2f, 0x61,
	0x72, 0x65, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_manage_v1_area_release_asset_proto_rawDescOnce sync.Once
	file_api_manage_v1_area_release_asset_proto_rawDescData = file_api_manage_v1_area_release_asset_proto_rawDesc
)

func file_api_manage_v1_area_release_asset_proto_rawDescGZIP() []byte {
	file_api_manage_v1_area_release_asset_proto_rawDescOnce.Do(func() {
		file_api_manage_v1_area_release_asset_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_manage_v1_area_release_asset_proto_rawDescData)
	})
	return file_api_manage_v1_area_release_asset_proto_rawDescData
}

var file_api_manage_v1_area_release_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_manage_v1_area_release_asset_proto_goTypes = []interface{}{
	(*CreateAreaReleaseAssetRequest)(nil), // 0: api.manage.v1.CreateAreaReleaseAssetRequest
	(*CreateAreaReleaseAssetReply)(nil),   // 1: api.manage.v1.CreateAreaReleaseAssetReply
	(*UpdateAreaReleaseAssetRequest)(nil), // 2: api.manage.v1.UpdateAreaReleaseAssetRequest
	(*UpdateAreaReleaseAssetReply)(nil),   // 3: api.manage.v1.UpdateAreaReleaseAssetReply
	(*DeleteAreaReleaseAssetRequest)(nil), // 4: api.manage.v1.DeleteAreaReleaseAssetRequest
	(*DeleteAreaReleaseAssetReply)(nil),   // 5: api.manage.v1.DeleteAreaReleaseAssetReply
	(*GetAreaReleaseAssetRequest)(nil),    // 6: api.manage.v1.GetAreaReleaseAssetRequest
	(*GetAreaReleaseAssetReply)(nil),      // 7: api.manage.v1.GetAreaReleaseAssetReply
	(*ListAreaReleaseAssetRequest)(nil),   // 8: api.manage.v1.ListAreaReleaseAssetRequest
	(*ListAreaReleaseAssetReply)(nil),     // 9: api.manage.v1.ListAreaReleaseAssetReply
}
var file_api_manage_v1_area_release_asset_proto_depIdxs = []int32{
	0, // 0: api.manage.v1.AreaReleaseAsset.CreateAreaReleaseAsset:input_type -> api.manage.v1.CreateAreaReleaseAssetRequest
	2, // 1: api.manage.v1.AreaReleaseAsset.UpdateAreaReleaseAsset:input_type -> api.manage.v1.UpdateAreaReleaseAssetRequest
	4, // 2: api.manage.v1.AreaReleaseAsset.DeleteAreaReleaseAsset:input_type -> api.manage.v1.DeleteAreaReleaseAssetRequest
	6, // 3: api.manage.v1.AreaReleaseAsset.GetAreaReleaseAsset:input_type -> api.manage.v1.GetAreaReleaseAssetRequest
	8, // 4: api.manage.v1.AreaReleaseAsset.ListAreaReleaseAsset:input_type -> api.manage.v1.ListAreaReleaseAssetRequest
	1, // 5: api.manage.v1.AreaReleaseAsset.CreateAreaReleaseAsset:output_type -> api.manage.v1.CreateAreaReleaseAssetReply
	3, // 6: api.manage.v1.AreaReleaseAsset.UpdateAreaReleaseAsset:output_type -> api.manage.v1.UpdateAreaReleaseAssetReply
	5, // 7: api.manage.v1.AreaReleaseAsset.DeleteAreaReleaseAsset:output_type -> api.manage.v1.DeleteAreaReleaseAssetReply
	7, // 8: api.manage.v1.AreaReleaseAsset.GetAreaReleaseAsset:output_type -> api.manage.v1.GetAreaReleaseAssetReply
	9, // 9: api.manage.v1.AreaReleaseAsset.ListAreaReleaseAsset:output_type -> api.manage.v1.ListAreaReleaseAssetReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_manage_v1_area_release_asset_proto_init() }
func file_api_manage_v1_area_release_asset_proto_init() {
	if File_api_manage_v1_area_release_asset_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_manage_v1_area_release_asset_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAreaReleaseAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAreaReleaseAssetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAreaReleaseAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAreaReleaseAssetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAreaReleaseAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAreaReleaseAssetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaReleaseAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaReleaseAssetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaReleaseAssetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_release_asset_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaReleaseAssetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_manage_v1_area_release_asset_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_manage_v1_area_release_asset_proto_goTypes,
		DependencyIndexes: file_api_manage_v1_area_release_asset_proto_depIdxs,
		MessageInfos:      file_api_manage_v1_area_release_asset_proto_msgTypes,
	}.Build()
	File_api_manage_v1_area_release_asset_proto = out.File
	file_api_manage_v1_area_release_asset_proto_rawDesc = nil
	file_api_manage_v1_area_release_asset_proto_goTypes = nil
	file_api_manage_v1_area_release_asset_proto_depIdxs = nil
}
