// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: api/manage/v1/area_polygon.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAreaPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAreaPolygonRequest) Reset() {
	*x = CreateAreaPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAreaPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaPolygonRequest) ProtoMessage() {}

func (x *CreateAreaPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaPolygonRequest.ProtoReflect.Descriptor instead.
func (*CreateAreaPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{0}
}

type CreateAreaPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAreaPolygonReply) Reset() {
	*x = CreateAreaPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAreaPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAreaPolygonReply) ProtoMessage() {}

func (x *CreateAreaPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAreaPolygonReply.ProtoReflect.Descriptor instead.
func (*CreateAreaPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{1}
}

type UpdateAreaPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAreaPolygonRequest) Reset() {
	*x = UpdateAreaPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAreaPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaPolygonRequest) ProtoMessage() {}

func (x *UpdateAreaPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaPolygonRequest.ProtoReflect.Descriptor instead.
func (*UpdateAreaPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{2}
}

type UpdateAreaPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAreaPolygonReply) Reset() {
	*x = UpdateAreaPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAreaPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAreaPolygonReply) ProtoMessage() {}

func (x *UpdateAreaPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAreaPolygonReply.ProtoReflect.Descriptor instead.
func (*UpdateAreaPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{3}
}

type DeleteAreaPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAreaPolygonRequest) Reset() {
	*x = DeleteAreaPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAreaPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaPolygonRequest) ProtoMessage() {}

func (x *DeleteAreaPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaPolygonRequest.ProtoReflect.Descriptor instead.
func (*DeleteAreaPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{4}
}

type DeleteAreaPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAreaPolygonReply) Reset() {
	*x = DeleteAreaPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAreaPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAreaPolygonReply) ProtoMessage() {}

func (x *DeleteAreaPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAreaPolygonReply.ProtoReflect.Descriptor instead.
func (*DeleteAreaPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{5}
}

type GetAreaPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAreaPolygonRequest) Reset() {
	*x = GetAreaPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaPolygonRequest) ProtoMessage() {}

func (x *GetAreaPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaPolygonRequest.ProtoReflect.Descriptor instead.
func (*GetAreaPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{6}
}

type GetAreaPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAreaPolygonReply) Reset() {
	*x = GetAreaPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAreaPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAreaPolygonReply) ProtoMessage() {}

func (x *GetAreaPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAreaPolygonReply.ProtoReflect.Descriptor instead.
func (*GetAreaPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{7}
}

type ListAreaPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAreaPolygonRequest) Reset() {
	*x = ListAreaPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaPolygonRequest) ProtoMessage() {}

func (x *ListAreaPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaPolygonRequest.ProtoReflect.Descriptor instead.
func (*ListAreaPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{8}
}

type ListAreaPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAreaPolygonReply) Reset() {
	*x = ListAreaPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_manage_v1_area_polygon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAreaPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAreaPolygonReply) ProtoMessage() {}

func (x *ListAreaPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_manage_v1_area_polygon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAreaPolygonReply.ProtoReflect.Descriptor instead.
func (*ListAreaPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_manage_v1_area_polygon_proto_rawDescGZIP(), []int{9}
}

var File_api_manage_v1_area_polygon_proto protoreflect.FileDescriptor

var file_api_manage_v1_area_polygon_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x72, 0x65, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65,
	0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x0a,
	0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x17, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x18, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x16, 0x0a,
	0x14, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xf7, 0x03, 0x0a, 0x0b, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x63, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x63, 0x0a, 0x11, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12,
	0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x63, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x12, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x5a, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x5d, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79,
	0x67, 0x6f, 0x6e, 0x12, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79,
	0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x72, 0x65, 0x61, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x43, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6e, 0x61, 0x72, 0x74, 0x6c, 0x75, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_manage_v1_area_polygon_proto_rawDescOnce sync.Once
	file_api_manage_v1_area_polygon_proto_rawDescData = file_api_manage_v1_area_polygon_proto_rawDesc
)

func file_api_manage_v1_area_polygon_proto_rawDescGZIP() []byte {
	file_api_manage_v1_area_polygon_proto_rawDescOnce.Do(func() {
		file_api_manage_v1_area_polygon_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_manage_v1_area_polygon_proto_rawDescData)
	})
	return file_api_manage_v1_area_polygon_proto_rawDescData
}

var file_api_manage_v1_area_polygon_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_manage_v1_area_polygon_proto_goTypes = []interface{}{
	(*CreateAreaPolygonRequest)(nil), // 0: api.manage.v1.CreateAreaPolygonRequest
	(*CreateAreaPolygonReply)(nil),   // 1: api.manage.v1.CreateAreaPolygonReply
	(*UpdateAreaPolygonRequest)(nil), // 2: api.manage.v1.UpdateAreaPolygonRequest
	(*UpdateAreaPolygonReply)(nil),   // 3: api.manage.v1.UpdateAreaPolygonReply
	(*DeleteAreaPolygonRequest)(nil), // 4: api.manage.v1.DeleteAreaPolygonRequest
	(*DeleteAreaPolygonReply)(nil),   // 5: api.manage.v1.DeleteAreaPolygonReply
	(*GetAreaPolygonRequest)(nil),    // 6: api.manage.v1.GetAreaPolygonRequest
	(*GetAreaPolygonReply)(nil),      // 7: api.manage.v1.GetAreaPolygonReply
	(*ListAreaPolygonRequest)(nil),   // 8: api.manage.v1.ListAreaPolygonRequest
	(*ListAreaPolygonReply)(nil),     // 9: api.manage.v1.ListAreaPolygonReply
}
var file_api_manage_v1_area_polygon_proto_depIdxs = []int32{
	0, // 0: api.manage.v1.AreaPolygon.CreateAreaPolygon:input_type -> api.manage.v1.CreateAreaPolygonRequest
	2, // 1: api.manage.v1.AreaPolygon.UpdateAreaPolygon:input_type -> api.manage.v1.UpdateAreaPolygonRequest
	4, // 2: api.manage.v1.AreaPolygon.DeleteAreaPolygon:input_type -> api.manage.v1.DeleteAreaPolygonRequest
	6, // 3: api.manage.v1.AreaPolygon.GetAreaPolygon:input_type -> api.manage.v1.GetAreaPolygonRequest
	8, // 4: api.manage.v1.AreaPolygon.ListAreaPolygon:input_type -> api.manage.v1.ListAreaPolygonRequest
	1, // 5: api.manage.v1.AreaPolygon.CreateAreaPolygon:output_type -> api.manage.v1.CreateAreaPolygonReply
	3, // 6: api.manage.v1.AreaPolygon.UpdateAreaPolygon:output_type -> api.manage.v1.UpdateAreaPolygonReply
	5, // 7: api.manage.v1.AreaPolygon.DeleteAreaPolygon:output_type -> api.manage.v1.DeleteAreaPolygonReply
	7, // 8: api.manage.v1.AreaPolygon.GetAreaPolygon:output_type -> api.manage.v1.GetAreaPolygonReply
	9, // 9: api.manage.v1.AreaPolygon.ListAreaPolygon:output_type -> api.manage.v1.ListAreaPolygonReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_manage_v1_area_polygon_proto_init() }
func file_api_manage_v1_area_polygon_proto_init() {
	if File_api_manage_v1_area_polygon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_manage_v1_area_polygon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAreaPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAreaPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAreaPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAreaPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAreaPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAreaPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAreaPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_manage_v1_area_polygon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAreaPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_manage_v1_area_polygon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_manage_v1_area_polygon_proto_goTypes,
		DependencyIndexes: file_api_manage_v1_area_polygon_proto_depIdxs,
		MessageInfos:      file_api_manage_v1_area_polygon_proto_msgTypes,
	}.Build()
	File_api_manage_v1_area_polygon_proto = out.File
	file_api_manage_v1_area_polygon_proto_rawDesc = nil
	file_api_manage_v1_area_polygon_proto_goTypes = nil
	file_api_manage_v1_area_polygon_proto_depIdxs = nil
}
