// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: component/app/app.proto

package app

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvName int32

const (
	EnvName_prod EnvName = 0
	EnvName_uat  EnvName = 1
	EnvName_sit  EnvName = 2
	EnvName_test EnvName = 3
	EnvName_dev  EnvName = 4
)

// Enum value maps for EnvName.
var (
	EnvName_name = map[int32]string{
		0: "prod",
		1: "uat",
		2: "sit",
		3: "test",
		4: "dev",
	}
	EnvName_value = map[string]int32{
		"prod": 0,
		"uat":  1,
		"sit":  2,
		"test": 3,
		"dev":  4,
	}
)

func (x EnvName) Enum() *EnvName {
	p := new(EnvName)
	*p = x
	return p
}

func (x EnvName) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvName) Descriptor() protoreflect.EnumDescriptor {
	return file_component_app_app_proto_enumTypes[0].Descriptor()
}

func (EnvName) Type() protoreflect.EnumType {
	return &file_component_app_app_proto_enumTypes[0]
}

func (x EnvName) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvName.Descriptor instead.
func (EnvName) EnumDescriptor() ([]byte, []int) {
	return file_component_app_app_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Debug       bool    `protobuf:"varint,1,opt,name=debug,proto3" json:"debug,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Env         EnvName `protobuf:"varint,3,opt,name=env,proto3,enum=component.app.EnvName" json:"env,omitempty"`
	RuntimePath string  `protobuf:"bytes,4,opt,name=runtime_path,json=runtimePath,proto3" json:"runtime_path,omitempty"`
	Proxy       string  `protobuf:"bytes,5,opt,name=proxy,proto3" json:"proxy,omitempty"`
	Pid         string  `protobuf:"bytes,6,opt,name=pid,proto3" json:"pid,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_component_app_app_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_component_app_app_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_component_app_app_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

func (x *Config) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Config) GetEnv() EnvName {
	if x != nil {
		return x.Env
	}
	return EnvName_prod
}

func (x *Config) GetRuntimePath() string {
	if x != nil {
		return x.RuntimePath
	}
	return ""
}

func (x *Config) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *Config) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

var File_component_app_app_proto protoreflect.FileDescriptor

var file_component_app_app_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x2f,
	0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x22, 0xa7, 0x01, 0x0a, 0x06, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x64, 0x65, 0x62, 0x75, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a,
	0x03, 0x65, 0x6e, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6f, 0x6d,
	0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x45, 0x6e, 0x76, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x03, 0x65, 0x6e, 0x76, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x75, 0x6e, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70,
	0x69, 0x64, 0x2a, 0x38, 0x0a, 0x07, 0x45, 0x6e, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x08, 0x0a,
	0x04, 0x70, 0x72, 0x6f, 0x64, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x75, 0x61, 0x74, 0x10, 0x01,
	0x12, 0x07, 0x0a, 0x03, 0x73, 0x69, 0x74, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x74, 0x65, 0x73,
	0x74, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x64, 0x65, 0x76, 0x10, 0x04, 0x42, 0x44, 0x0a, 0x0d,
	0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x61, 0x70, 0x70, 0x50, 0x01, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6e, 0x61, 0x72,
	0x74, 0x6c, 0x75, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x70, 0x3b, 0x61,
	0x70, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_component_app_app_proto_rawDescOnce sync.Once
	file_component_app_app_proto_rawDescData = file_component_app_app_proto_rawDesc
)

func file_component_app_app_proto_rawDescGZIP() []byte {
	file_component_app_app_proto_rawDescOnce.Do(func() {
		file_component_app_app_proto_rawDescData = protoimpl.X.CompressGZIP(file_component_app_app_proto_rawDescData)
	})
	return file_component_app_app_proto_rawDescData
}

var file_component_app_app_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_component_app_app_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_component_app_app_proto_goTypes = []interface{}{
	(EnvName)(0),   // 0: component.app.EnvName
	(*Config)(nil), // 1: component.app.Config
}
var file_component_app_app_proto_depIdxs = []int32{
	0, // 0: component.app.Config.env:type_name -> component.app.EnvName
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_component_app_app_proto_init() }
func file_component_app_app_proto_init() {
	if File_component_app_app_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_component_app_app_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_component_app_app_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_component_app_app_proto_goTypes,
		DependencyIndexes: file_component_app_app_proto_depIdxs,
		EnumInfos:         file_component_app_app_proto_enumTypes,
		MessageInfos:      file_component_app_app_proto_msgTypes,
	}.Build()
	File_component_app_app_proto = out.File
	file_component_app_app_proto_rawDesc = nil
	file_component_app_app_proto_goTypes = nil
	file_component_app_app_proto_depIdxs = nil
}
