// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: api/v1/area/polygon.proto

package area

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePolygonRequest) Reset() {
	*x = CreatePolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolygonRequest) ProtoMessage() {}

func (x *CreatePolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolygonRequest.ProtoReflect.Descriptor instead.
func (*CreatePolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{0}
}

type CreatePolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePolygonReply) Reset() {
	*x = CreatePolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolygonReply) ProtoMessage() {}

func (x *CreatePolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolygonReply.ProtoReflect.Descriptor instead.
func (*CreatePolygonReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{1}
}

type UpdatePolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePolygonRequest) Reset() {
	*x = UpdatePolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolygonRequest) ProtoMessage() {}

func (x *UpdatePolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolygonRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{2}
}

type UpdatePolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePolygonReply) Reset() {
	*x = UpdatePolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolygonReply) ProtoMessage() {}

func (x *UpdatePolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolygonReply.ProtoReflect.Descriptor instead.
func (*UpdatePolygonReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{3}
}

type DeletePolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePolygonRequest) Reset() {
	*x = DeletePolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolygonRequest) ProtoMessage() {}

func (x *DeletePolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolygonRequest.ProtoReflect.Descriptor instead.
func (*DeletePolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{4}
}

type DeletePolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePolygonReply) Reset() {
	*x = DeletePolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolygonReply) ProtoMessage() {}

func (x *DeletePolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolygonReply.ProtoReflect.Descriptor instead.
func (*DeletePolygonReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{5}
}

type GetPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPolygonRequest) Reset() {
	*x = GetPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolygonRequest) ProtoMessage() {}

func (x *GetPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolygonRequest.ProtoReflect.Descriptor instead.
func (*GetPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{6}
}

type GetPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPolygonReply) Reset() {
	*x = GetPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolygonReply) ProtoMessage() {}

func (x *GetPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolygonReply.ProtoReflect.Descriptor instead.
func (*GetPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{7}
}

type ListPolygonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPolygonRequest) Reset() {
	*x = ListPolygonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPolygonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPolygonRequest) ProtoMessage() {}

func (x *ListPolygonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPolygonRequest.ProtoReflect.Descriptor instead.
func (*ListPolygonRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{8}
}

type ListPolygonReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPolygonReply) Reset() {
	*x = ListPolygonReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_area_polygon_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPolygonReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPolygonReply) ProtoMessage() {}

func (x *ListPolygonReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_area_polygon_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPolygonReply.ProtoReflect.Descriptor instead.
func (*ListPolygonReply) Descriptor() ([]byte, []int) {
	return file_api_v1_area_polygon_proto_rawDescGZIP(), []int{9}
}

var File_api_v1_area_polygon_proto protoreflect.FileDescriptor

var file_api_v1_area_polygon_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x2f, 0x70, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x14, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0xa3, 0x03, 0x0a, 0x07, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x12, 0x53, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f,
	0x6e, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72,
	0x65, 0x61, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x61, 0x72, 0x65, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0d, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x21, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x4a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x1e, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x6c,
	0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f,
	0x6c, 0x79, 0x67, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x41, 0x0a, 0x0b, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x50, 0x01, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6e, 0x61, 0x72, 0x74, 0x6c, 0x75, 0x2f,
	0x61, 0x72, 0x65, 0x61, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x3b, 0x61, 0x72, 0x65, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_area_polygon_proto_rawDescOnce sync.Once
	file_api_v1_area_polygon_proto_rawDescData = file_api_v1_area_polygon_proto_rawDesc
)

func file_api_v1_area_polygon_proto_rawDescGZIP() []byte {
	file_api_v1_area_polygon_proto_rawDescOnce.Do(func() {
		file_api_v1_area_polygon_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_area_polygon_proto_rawDescData)
	})
	return file_api_v1_area_polygon_proto_rawDescData
}

var file_api_v1_area_polygon_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_area_polygon_proto_goTypes = []interface{}{
	(*CreatePolygonRequest)(nil), // 0: api.v1.area.CreatePolygonRequest
	(*CreatePolygonReply)(nil),   // 1: api.v1.area.CreatePolygonReply
	(*UpdatePolygonRequest)(nil), // 2: api.v1.area.UpdatePolygonRequest
	(*UpdatePolygonReply)(nil),   // 3: api.v1.area.UpdatePolygonReply
	(*DeletePolygonRequest)(nil), // 4: api.v1.area.DeletePolygonRequest
	(*DeletePolygonReply)(nil),   // 5: api.v1.area.DeletePolygonReply
	(*GetPolygonRequest)(nil),    // 6: api.v1.area.GetPolygonRequest
	(*GetPolygonReply)(nil),      // 7: api.v1.area.GetPolygonReply
	(*ListPolygonRequest)(nil),   // 8: api.v1.area.ListPolygonRequest
	(*ListPolygonReply)(nil),     // 9: api.v1.area.ListPolygonReply
}
var file_api_v1_area_polygon_proto_depIdxs = []int32{
	0, // 0: api.v1.area.Polygon.CreatePolygon:input_type -> api.v1.area.CreatePolygonRequest
	2, // 1: api.v1.area.Polygon.UpdatePolygon:input_type -> api.v1.area.UpdatePolygonRequest
	4, // 2: api.v1.area.Polygon.DeletePolygon:input_type -> api.v1.area.DeletePolygonRequest
	6, // 3: api.v1.area.Polygon.GetPolygon:input_type -> api.v1.area.GetPolygonRequest
	8, // 4: api.v1.area.Polygon.ListPolygon:input_type -> api.v1.area.ListPolygonRequest
	1, // 5: api.v1.area.Polygon.CreatePolygon:output_type -> api.v1.area.CreatePolygonReply
	3, // 6: api.v1.area.Polygon.UpdatePolygon:output_type -> api.v1.area.UpdatePolygonReply
	5, // 7: api.v1.area.Polygon.DeletePolygon:output_type -> api.v1.area.DeletePolygonReply
	7, // 8: api.v1.area.Polygon.GetPolygon:output_type -> api.v1.area.GetPolygonReply
	9, // 9: api.v1.area.Polygon.ListPolygon:output_type -> api.v1.area.ListPolygonReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_area_polygon_proto_init() }
func file_api_v1_area_polygon_proto_init() {
	if File_api_v1_area_polygon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_area_polygon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPolygonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_area_polygon_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPolygonReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_area_polygon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_area_polygon_proto_goTypes,
		DependencyIndexes: file_api_v1_area_polygon_proto_depIdxs,
		MessageInfos:      file_api_v1_area_polygon_proto_msgTypes,
	}.Build()
	File_api_v1_area_polygon_proto = out.File
	file_api_v1_area_polygon_proto_rawDesc = nil
	file_api_v1_area_polygon_proto_goTypes = nil
	file_api_v1_area_polygon_proto_depIdxs = nil
}
