apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "github.com/cnartlu/area-service.fullname" . }}
  labels:
  {{- include "github.com/cnartlu/area-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}