apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.imagePull.name }}
  labels:
    {{- include "github.com/cnartlu/area-service.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  {{- toYaml .Values.secret.imagePull.data | nindent 2 }}