{{- if and .Values.ingress.enabled .Values.ingress.tls.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.tls.name }}
  labels:
    {{- include "github.com/cnartlu/area-service.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- toYaml .Values.secret.tls.data | nindent 2 }}
{{- end }}
