apiVersion: v1
kind: Service
metadata:
  name: {{ include "github.com/cnartlu/area-service.fullname" . }}
  labels:
    {{- include "github.com/cnartlu/area-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
  {{- end }}
  selector:
    {{- include "github.com/cnartlu/area-service.selectorLabels" . | nindent 4 }}
